---
- hosts: all
  gather_facts: false

  tasks:

  - name: Run show version on remote devices
    cisco.ios.ios_command:
      commands: show version
    register: version_output
  
  - debug:
      var: version_output.stdout_lines